CREATE TABLE USERS (
   ID BIGINT PRIMARY KEY UNIQUE NOT NULL,
   LOGIN VARCHAR(255) NOT NULL UNIQUE,
   PASSWORD VARCHAR(255) NOT NULL,
   ROLE TINYINT NOT NULL
);
CREATE TABLE SCORE (
   ID BIGINT PRIMARY KEY UNIQUE NOT NULL,
   DESCRIPTION VARCHAR(255) NOT NULL,
   MIN INTEGER NOT NULL,
   MAX INTEGER NOT NULL
);